### ISSUE TITLE
Get custom token balance example

### ISSUE THREAD

**Issue by Viltrum** [clbrge/svelte-web3#10]
It would be super helpful for blockchain beginners like me if there was an example how to get a custom token balance of an address.

**Comment by clbrge** [comment]
$web3 is the instance of Web3 so just to something like :
let contract = new $web3.eth.Contract(tokenABI,tokenAddress);
async function getBalance() {
  balance = await contract.methods.balanceOf(walletAddress);
  return balance;
}
generally all help you can find on internet for web.js is valid, just use $web3 instead of web3.
