### ISSUE TITLE
Issue with svelte-web3 as a dependency

### ISSUE THREAD

**Issue by pythonicode** [clbrge/svelte-web3#27]
Hey, I'm working on a package and I'm using svelte-web3 as a dependency and I'm getting this problem (it might be on my end but I can't seem to figure it out)

> No "exports" main defined in C:\Users\antho\Desktop\Work\Cointrack\Web\cointrack\node_modules\svelte-contracts\node_modules\svelte-web3\package.json imported from C:\Users\antho\Desktop\Work\Cointrack\Web\cointrack\node_modules\svelte-contracts\dist\index.js

Here is the repository:  https://github.com/PythoniCode/svelte-contracts

**Comment by clbrge** [comment]
So the problem appears when you are trying to use 'svelte-contracts' from another repo, right ?
Looks like you build process is complaining that it cannot find the exports it needs... 
Hard to tell you more since i cannot reproduce the call that produce this output.
maybe you could give me another small repo that use svelte-contracts (just the minimum to reproduce this problem)

**Comment by pythonicode** [comment]
Yes, here is an initial Svelte Kit project with just my package added as in import.

https://github.com/PythoniCode/svelte-contracts-test

Thanks for looking into it.

**Comment by pythonicode** [comment]
It seems to only be a problem with the way I'm using it in my package. Importing the latest version of svelte-web3 does not cause any problems, however, importing svelte-contracts is causing the above error.

**Comment by clbrge** [comment]
I will close the bug for now. reopen if you still have problem...
