### ISSUE TITLE
Calling setProvider throws 4100

### ISSUE THREAD

**Issue by yaeszlo** [clbrge/svelte-web3#39]
Hello

When calling to `setProvider` on `defaultEvmStores` I get an error 
```
{
    "code": 4100,
    "message": "The requested account and/or method has not been authorized by the user."
}
```

The wallet I am using is Metamask.
I have no idea what could be happening, but it seems recently the values provided from `chainId` store changed format, perhaps that could be related? 
The issue occurs on Opera where I tested the wallet connection before (worked without any problems), and then after a while deployed a new version of the website. Then it stopped working.
On Opera I have Metamask with 2 accounts and 2 networks configured - ETH mainnet and BSC
I have just performed a test with freshly installed Metamask in Chrome, on the same website deployed on the same CDN and it works. 

my code is pretty simple, but I'll paste it anyway:
```
async function unlockWallet() {
	await defaultEvmStores.setProvider()
}
```

this function is called when user is pressing a button.

**Comment by clbrge** [comment]
That's the expected behavior. You have to use try catch in you app code either ignore the throw or handle it with the desired UX flow...
The throw is generated by Metamask so if the reason is not "The requested account and/or method has not been authorized by the user." the problem may origin from a bug in Metamask...
